# azure-pipelines-backend.yml
# This pipeline builds and deploys the ASP.NET Core backend to Azure App Service

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureAppName: 'mywebapp047'

steps:
- checkout: self
  clean: true
  fetchDepth: 1

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
  displayName: 'Install .NET SDK'

- script: |
    cd Edu_sync_final_project
    dotnet restore Edu_sync_final_project.sln
  displayName: 'Restore Dependencies'

- script: |
    cd Edu_sync_final_project
    dotnet build Edu_sync_final_project.sln --configuration $(buildConfiguration) --no-restore
  displayName: 'Build .NET Project'

- script: |
    cd Edu_sync_final_project
    dotnet publish Edu_sync_final_project.sln -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) --no-build
  displayName: 'Publish .NET Project'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureConnection047'
    appType: 'webApp'
    appName: '$(azureAppName)'
    package: '$(Build.ArtifactStagingDirectory)'
    deploymentMethod: 'auto'
  displayName: 'Deploy to Azure App Service'
