// <auto-generated />
using System;
using Edu_sync_final_project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Edu_sync_final_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Edu_sync_final_project.Models.AssessmentModel", b =>
                {
                    b.Property<Guid>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MaxScore")
                        .HasColumnType("int");

                    b.Property<string>("Questions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("AssessmentId");

                    b.HasIndex("CourseId");

                    b.ToTable("AssessmentModel", (string)null);
                });

            modelBuilder.Entity("Edu_sync_final_project.Models.CourseModel", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CourseModel", (string)null);
                });

            modelBuilder.Entity("Edu_sync_final_project.Models.ResultModel", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid?>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AttemptDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResultId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("UserId");

                    b.ToTable("ResultModel", (string)null);
                });

            modelBuilder.Entity("Edu_sync_final_project.Models.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(225)
                        .IsUnicode(false)
                        .HasColumnType("varchar(225)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(128)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("UserModel", (string)null);
                });

            modelBuilder.Entity("Edu_sync_final_project.Models.AssessmentModel", b =>
                {
                    b.HasOne("Edu_sync_final_project.Models.CourseModel", "Course")
                        .WithMany("AssessmentModels")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK_AssessmentModel_CourseModel");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Edu_sync_final_project.Models.CourseModel", b =>
                {
                    b.HasOne("Edu_sync_final_project.Models.UserModel", "Instructor")
                        .WithMany("CourseModels")
                        .HasForeignKey("InstructorId")
                        .HasConstraintName("FK_CourseModel_UserModel");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Edu_sync_final_project.Models.ResultModel", b =>
                {
                    b.HasOne("Edu_sync_final_project.Models.AssessmentModel", "Assessment")
                        .WithMany("ResultModels")
                        .HasForeignKey("AssessmentId")
                        .HasConstraintName("FK_ResultModel_AssessmentModel");

                    b.HasOne("Edu_sync_final_project.Models.UserModel", "User")
                        .WithMany("ResultModels")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ResultModel_UserModel");

                    b.Navigation("Assessment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Edu_sync_final_project.Models.AssessmentModel", b =>
                {
                    b.Navigation("ResultModels");
                });

            modelBuilder.Entity("Edu_sync_final_project.Models.CourseModel", b =>
                {
                    b.Navigation("AssessmentModels");
                });

            modelBuilder.Entity("Edu_sync_final_project.Models.UserModel", b =>
                {
                    b.Navigation("CourseModels");

                    b.Navigation("ResultModels");
                });
#pragma warning restore 612, 618
        }
    }
}
